# Generated by Django 5.2.2 on 2025-06-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0002_financialyear_budget_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='name',
            field=models.CharField(max_length=9),
        ),
        migrations.AddConstraint(
            model_name='financialyear',
            constraint=models.UniqueConstraint(fields=('name', 'budget_source'), name='unique_financial_year_budget_source'),
        ),
    ]
